FROM postgres

ENV USER pttg
ENV GROUP pttg

WORKDIR /app

RUN groupadd -r ${GROUP} && \
    useradd -r -g ${USER} ${GROUP} -d /app && \
    mkdir -p /app && \
    chown -R ${USER}:${GROUP} /app

COPY run-pttg-postgres.sh /app

RUN chmod a+x /app/run-pttg-postgres.sh

ENTRYPOINT /app/run-pttg-postgres.sh
