package uk.gov.digital.ho.proving.income.audit;

public enum AuditEventType {
    INCOME_PROVING_FINANCIAL_STATUS_REQUEST,
    INCOME_PROVING_FINANCIAL_STATUS_RESPONSE,

    INCOME_PROVING_INCOME_CHECK_REQUEST,
    INCOME_PROVING_INCOME_CHECK_RESPONSE,
}
