package uk.gov.digital.ho.proving.income.api.domain;

public enum FinancialCheckValues {
    NON_CONSECUTIVE_MONTHS,
    MONTHLY_VALUE_BELOW_THRESHOLD,
    MONTHLY_SALARIED_PASSED,
    NOT_ENOUGH_RECORDS,
    WEEKLY_SALARIED_PASSED,
    WEEKLY_VALUE_BELOW_THRESHOLD,
    PAY_FREQUENCY_CHANGE,
    MULTIPLE_EMPLOYERS,
    UNKNOWN_PAY_FREQUENCY
}
